version: '3.8'

services:
  db:
    container_name: 'mysql-dashsprint'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
  app:
    container_name: 'app-dashsprint'
    depends_on:
      - db
    build: .
    command: sh -c "npm install -g nodemon && npm install && npm start"
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/app
      - .:/usr/src/app/node_modules
    environment:
      NODE_ENV: development

volumes:
  db: